name: login_signup
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  animate_do: ^4.2.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.12
  google_sign_in: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
    - assets/background.jpg
    - assets/illustrator.jpg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "app_icon.png"
  min_sdk_android: 21
